services:
  - type: web
    name: uac-game
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: maaazeeee
